export const brandMedia = {
  companyGroupPortrait: {
    src: "/images/nelviusgrey/company-group-portrait.png",
    alt: "A group portrait in a NelviusGrey Tech-branded Lagos workspace.",
    route: "/about",
    section: "brand-origin",
    orientation: "landscape-4:3",
    focalPoint: "The people and the NelviusGrey Tech wall sign across the centre.",
    faces: "Distributed across the full width, with the closest faces at both outer edges.",
    logo: "Large wall sign at the upper centre; preserve the full wordmark.",
    textSafety: "Keep text outside the photograph.",
    objectPosition: {
      desktop: "50% 48%",
      tablet: "50% 50%",
      mobile: "50% 50%",
    },
    motion: {
      reveal: "cinematic-mask",
      scroll: "subtle-vertical-parallax",
      hover: "soft-perspective-depth",
      mobile: "scale-fade",
      reducedMotion: "fade",
    },
    label: "Lagos studio / people",
    caption: "A human practice built around collaboration, context and craft.",
    shape: "portrait" as const,
  },
  cybersecurityAnalysis: {
    src: "/images/nelviusgrey/cybersecurity-analysis.png",
    alt: "Technology professionals reviewing a secure digital system in a dark workspace.",
    route: "/services",
    section: "capability-experience",
    orientation: "landscape-16:9",
    focalPoint: "The two foreground professionals and transparent system interface.",
    faces: "Centre-right; retain comfortable space above and below.",
    logo: "Branded glass wall at the far right; keep visible on desktop and tablet.",
    textSafety: "Left third can carry small labels only; keep core copy outside.",
    objectPosition: {
      desktop: "58% 50%",
      tablet: "60% 50%",
      mobile: "58% 50%",
    },
    motion: {
      reveal: "diagonal-aperture",
      scroll: "reverse-parallax",
      hover: "interface-glare",
      mobile: "scale-fade",
      reducedMotion: "fade",
    },
    label: "Secure systems / capability",
    caption: "Human judgement and technical depth, working as one system.",
    shape: "technical" as const,
  },
  engineeringWorkstation: {
    src: "/images/nelviusgrey/engineering-workstation.png",
    alt: "A software professional working across code and data-monitoring screens.",
    route: "/",
    section: "connected-practice",
    orientation: "landscape-16:9",
    focalPoint: "The engineer at centre-right and the three primary screens.",
    faces: "Centre-right profile; avoid a tight right-edge crop.",
    logo: "Upper-right wall mark and lower-left mug mark; prioritise the wall mark.",
    textSafety: "Keep narrative copy in a separate adjacent column.",
    objectPosition: {
      desktop: "54% 50%",
      tablet: "56% 50%",
      mobile: "61% 50%",
    },
    motion: {
      reveal: "cinematic-mask",
      scroll: "subtle-horizontal-parallax",
      hover: "soft-perspective-depth",
      mobile: "scale-fade",
      reducedMotion: "fade",
    },
    label: "Engineering discipline",
    caption: "From architecture and data to software that works in the real world.",
    shape: "editorial" as const,
  },
  collaborativeSystemReview: {
    src: "/images/nelviusgrey/collaborative-system-review.png",
    alt: "A multidisciplinary group reviewing a digital system around an interactive table.",
    route: "/work",
    section: "project-exhibition",
    orientation: "landscape-16:9",
    focalPoint: "The central presenter, surrounding group and illuminated table interface.",
    faces: "Across the upper half; preserve the central presenter.",
    logo: "Centre-left wall mark; keep visible in wide and tablet crops.",
    textSafety: "Only compact metadata may sit at the bottom edge.",
    objectPosition: {
      desktop: "50% 50%",
      tablet: "50% 50%",
      mobile: "51% 50%",
    },
    motion: {
      reveal: "horizontal-curtain",
      scroll: "subtle-vertical-parallax",
      hover: "table-light-response",
      mobile: "scale-fade",
      reducedMotion: "fade",
    },
    label: "Collaborative delivery",
    caption: "Complex decisions become clearer when disciplines meet around the same problem.",
    shape: "panorama" as const,
  },
  productDataReview: {
    src: "/images/nelviusgrey/product-data-review.png",
    alt: "A product group reviewing dashboards and interface flows on a large display.",
    route: "/solutions",
    section: "sector-switcher",
    orientation: "landscape-16:9",
    focalPoint: "The presenter, group and dashboard wall on the right.",
    faces: "Left and centre; the right side is the interface focal area.",
    logo: "Upper-left background panel; maintain visibility on desktop.",
    textSafety: "Keep descriptive text beside the photograph.",
    objectPosition: {
      desktop: "54% 50%",
      tablet: "58% 50%",
      mobile: "62% 50%",
    },
    motion: {
      reveal: "diagonal-aperture",
      scroll: "reverse-parallax",
      hover: "interface-glare",
      mobile: "scale-fade",
      reducedMotion: "fade",
    },
    label: "Operational intelligence",
    caption: "Interfaces shaped around the decisions people need to make.",
    shape: "technical" as const,
  },
  cloudInfrastructure: {
    src: "/images/nelviusgrey/cloud-infrastructure.png",
    alt: "A technology professional monitoring cloud infrastructure in a server environment.",
    route: "/contact",
    section: "project-contact",
    orientation: "landscape-16:9",
    focalPoint: "The professional on the left and cloud-security visualisation on the right.",
    faces: "Left third; preserve space around the profile.",
    logo: "Large illuminated mark in the lower-left background; keep visible.",
    textSafety: "The lower edge supports a compact caption; no body copy overlay.",
    objectPosition: {
      desktop: "53% 50%",
      tablet: "54% 50%",
      mobile: "48% 50%",
    },
    motion: {
      reveal: "vertical-aperture",
      scroll: "subtle-horizontal-parallax",
      hover: "infrastructure-scan",
      mobile: "scale-fade",
      reducedMotion: "fade",
    },
    label: "Infrastructure / foundations",
    caption: "Secure, scalable foundations for products that need to keep working.",
    shape: "infrastructure" as const,
  },
} as const;

export type BrandMediaKey = keyof typeof brandMedia;
